version: '2'

services:
  gitpitch:
    image: knsit/gitpitch:latest
    environment:
      - "GP_GITLAB_BASE=http://gitlab/"
      - "GP_GITLAB_API=http://gitlab/api/v4/"
      - "GP_GITLAB_AS_DEFAULT=true"
    ports:
      - 9000:9000
    volumes:
      - .:/code
      #- '/data/code/gitlab/gitpitch/conf:/gitpitch/conf'
    links:
      - "gitlab:gitlab"
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab/'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8081:80'
      - '443:443'
      - '8022:22'
    volumes:
      - '/data/code/gitlab/config:/etc/gitlab'
      - '/data/code/gitlab/logs:/var/log/gitlab'
      - '/data/code/gitlab/data:/var/opt/gitlab'
