version: '2'
services:
    gitpitch:
        image: knsit/gitpitch:latest
        environment:
            - "GP_GITLAB_BASE=http://gitlab/"
            - "GP_GITLAB_API=http://gitlab/api/v4/"
            - "GP_GITLAB_AS_DEFAULT=true"
        ports:
            - 9000:9000
        volumes:
            - .:/code
        links:
            - "gitlab:gitlab"
    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        hostname: 'gitlab'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
              external_url 'http://gitlab/'
              # Add any other gitlab.rb configuration here, each on its own line
        ports:
        - '8081:80'
        - '443:443'
        - '8022:22'
        volumes:
        - '/srv/gitlab/config:/etc/gitlab'
        - '/srv/gitlab/logs:/var/log/gitlab'
        - '/srv/gitlab/data:/var/opt/gitlab'
